#!/usr/bin/env bash

# Some Default Variables
clear && LC_ALL=C && LANG=C
export ROOTSZ="+50G"
export HOMESZ="0" # Remaining space
export BOOTSZ="+512M"
export BIOSSZ="+1M"

ascii() {
	echo ' $$$$$$\                      $$\             $$$$$$\                       $$\               $$\ $$\ '
	echo '$$  __$$\                     $$ |            \_$$  _|                      $$ |              $$ |$$ |'
	echo '$$ /  $$ | $$$$$$\   $$$$$$$\ $$$$$$$\          $$ |  $$$$$$$\   $$$$$$$\ $$$$$$\    $$$$$$\  $$ |$$ |'
	echo '$$$$$$$$ |$$  __$$\ $$  _____|$$  __$$\         $$ |  $$  __$$\ $$  _____|\_$$  _|   \____$$\ $$ |$$ |'
	echo '$$  __$$ |$$ |  \__|$$ /      $$ |  $$ |        $$ |  $$ |  $$ |\$$$$$$\    $$ |     $$$$$$$ |$$ |$$ |'
	echo '$$ |  $$ |$$ |      $$ |      $$ |  $$ |        $$ |  $$ |  $$ | \____$$\   $$ |$$\ $$  __$$ |$$ |$$ |'
	echo '$$ |  $$ |$$ |      \$$$$$$$\ $$ |  $$ |      $$$$$$\ $$ |  $$ |$$$$$$$  |  \$$$$  |\$$$$$$$ |$$ |$$ |'
	echo '\__|  \__|\__|       \_______|\__|  \__|      \______|\__|  \__|\_______/    \____/  \_______|\__|\__|'
	echo '                                                                                                      '
	echo '# EDIT BEFORE USING. NO ONE WILL BE RESPONSIBLE IF ANYTHING WENT WRONG.                               '
	echo '# CREDITS == https://github.com/prmsrswt/arch-install                                                 '
	echo '# PRO USER MEANS WHO KNOW WHATS HAPPENING IN BACKGROUND OF SCRIPT.                                    '
}

br() { for ((i = 1; i <= $(tput cols); i++)); do echo -n -; done; }

TABLEGPT() {
	echo """$DRIVE2EDIT""1 ROOT = $ROOTSZ"
	echo """$DRIVE2EDIT""2 HOME = $HOMESZ"
	echo """$DRIVE2EDIT""3 BOOT = $BOOTSZ"
	echo """$DRIVE2EDIT""4 BIOS = $BIOSSZ"
}

updates() {
	if [ "$EUID" -ne 0 ]; then
		echo "Please run as root" && exit
		if : >/dev/tcp/8.8.8.8/53; then
			true
		else echo 'Offline Please connect...[Use iwctl command then type help]' && exit; fi
	fi
	timedatectl set-ntp true
	pacman -Syy
}

partition() {
	clear && echo -e '1. Create New partition table [Recommended for new installs]'
	echo -e '2. Edit Old partition table with cgdisk [Only for Pro user]'
	echo -e '3. Skip partition [Only for Pro user]'
	read -rp ': ' OLDNEW
	if [[ "$OLDNEW" = '1' ]]; then
		read -rp "Which drive you want to partition (example /dev/sda): " DRIVE2EDIT
		clear && br && echo "We will create and format the partitions as follows:" && TABLEGPT && br
		read -rp 'Want to edit   [Y/N]: ' FSOK
		if [[ "$FSOK" = 'y' ]] || [[ "$FSOK" = 'Y' ]]; then
			clear
			echo "Enter Size For   /Root    [Default= $ROOTSZ][Use 0 For All Free Space & G=Gb;M=Mb & ctrl+c For Default]"
			read -re -i "$ROOTSZ" ROOTSZ
			clear
			echo "Enter Size For   /Home    [Default= $HOMESZ][Use 0 For All Free Space & G=Gb;M=Mb & ctrl+c For Default]"
			read -re -i "$HOMESZ" HOMESZ
			clear
			echo "Enter Size For   /Boot    [Default= $BOOTSZ][Use 0 For All Free Space & G=Gb;M=Mb & ctrl+c For Default]"
			read -re -i "$BOOTSZ" BOOTSZ
			clear
			echo "Enter Size For   /Bios    [Default= $ROOTSZ][Use 0 For All Free Space & G=Gb;M=Mb & ctrl+c For Default]"
			read -re -i "$BIOSSZ" BIOSSZ
		fi
		clear && br && TABLEGPT && lsblk && br
		read -rp 'All Good   [Y/N]: ' FSOK
		if [[ "$FSOK" =~ ^[Yy]$ ]]; then
			# Make partition table {x:x:x}=={partition_no:starting_block:desired_size}
			sgdisk -Z "$DRIVE2EDIT"                                     # Destroy existing mbr or gpt structures on disk
			sgdisk -a 4096 -o                                           # New gpt disk 4096 alignment
			sgdisk -n 1:0:"$ROOTSZ" -t 1:8300 -c 1:"ROOT" "$DRIVE2EDIT" # Part 1 (ROOT), default start, 60GB
			sgdisk -n 3:0:"$BOOTSZ" -t 3:ef00 -c 3:"BOOT" "$DRIVE2EDIT" # Part 4 (BOOT), default start, 512MB
			sgdisk -n 4:0:"$BIOSSZ" -t 4:ef02 -c 4:"BIOS" "$DRIVE2EDIT" # Part 5 (BIOS), default start, 1MB
			sgdisk -n 2:0:"$HOMESZ" -t 2:8300 -c 2:"HOME" "$DRIVE2EDIT" # Part 2 (HOME), default start, Remaning space
			# Inform the OS of partition table changes
			sgdisk -p "$DRIVE2EDIT"
			clear && br && echo "Press any key to write partition table to disk or ctrl+c to exit" && br
			read -r
			partprobe "$DRIVE2EDIT"
		else
			clear && lsblk && br
			read -rp "Which drive you want to partition [Exit with ctrl+c] (example /dev/sda)   " DRIVE2EDIT
			# Using cgdisk for GPT, for mbr use cfdisk
			cgdisk "$DRIVE2EDIT"
		fi
	elif [ "$OLDNEW" = '2' ]; then
		clear && lsblk && br
		read -rp "Which drive you want to partition [Exit with ctrl+c] (example /dev/sda)   " DRIVE2EDIT
		# Using cgdisk for GPT, for mbr use cfdisk
		cgdisk "$DRIVE2EDIT"
	elif [ "$OLDNEW" = '3' ]; then
		true
	else
		exit
	fi
}

mounter() {
	# Root
	clear && lsblk && br
	read -rp "Which is your root partition [Eg. /dev/sda3]: " ROOTP
	mkfs.ext4 "$ROOTP"
	mount -o "defaults,noatime" "$ROOTP" /mnt
	mkdir -pv /mnt/{boot/efi,home}
	# Home
	clear && lsblk && br
	read -rp "Do you want to mount seperate home partition [y/N]: " RESPH
	if [[ "$RESPH" =~ ^[Yy]$ ]]; then
		read -rp 'Which is your home partition [Eg. /dev/sda4]: ' HOMEP
		read -rp 'Do you want to ***FORMAT*** /home partition [Y/N]: '
		read -rp 'Do you want to **FORMAT** /home partition [Confirm][Y/N]: ' RESPRMH && sleep 5
		if [[ "$RESPRMH" =~ ^[Yy]$ ]]; then
			mkfs.ext4 "$HOMEP"
		fi
		mount -o "defaults,noatime,nosuid,nodev" "$HOMEP" /mnt/home
	fi
	# Boot
	clear && lsblk && br
	read -rp "Which is your boot partition [Eg. /dev/sda1]: " BOOTP
	mkfs.fat -F32 "$BOOTP"
	mount -o "defaults,noatime,nosuid,nodev" "$BOOTP" /mnt/boot/efi
	# Swap
	clear && lsblk && br
	read -rp "Do you want to mount seperate SWAP partition [Y/N]: " RESPS
	if [[ "$RESPS" =~ ^[Yy]$ ]]; then
		read -rp "Which Is Your Swap Partition [Eg. /dev/sda2]: " SWAPP
		mkswap "$SWAPP"
		swapon "$SWAPP"
	fi
}

base() {
	#br && read -rp "Do you want to use your old saved packages directory [FOR PRO USER ONLY] [Y/N]: " PACBDIR
	#if [[ "$PACBDIR" =~ ^[Yy]$ ]]; then
	#	pacstrap -U /mnt /mnt/home/PKG/*base-2-2*xz || pacstrap /mnt base
	#	sed -i 's|#CacheDir    = /var/cache/pacman/pkg/|CacheDir    = /home/PKG/|g' /mnt/etc/pacman.conf
	#	sed -i 's|#CacheDir    = /var/cache/pacman/pkg/|CacheDir    = /mnt/home/PKG/|g' /etc/pacman.conf
	#fi
	pacstrap /mnt base linux-firmware linux-zen linux-zen-headers base-devel grub efibootmgr nano sudo git \
		networkmanager bluez ufw pipewire{,-pulse,-media-session} alacritty ttf-jetbrains-mono ttf-lato \
		lm_sensors thermald
	genfstab -U /mnt >/mnt/etc/fstab
}

chrooot() {
	curl -sL https://raw.githubusercontent.com/Jrchintu/Arch/main/chroot -o /mnt/chroot
	arch-chroot /mnt bash -c "chmod a+x /chroot.sh && bash /chroot.sh && exit"
}

denv() {
	br && echo -e "Choose a Desktop Environment to install: \n"
	echo -e "1. GNOME \n2. DEEPIN \n3. KDE \n4. XFCE \n5. LXQT"
	read -rp "DE[1-5]: " DESKTOPENV
	if [[ "$DESKTOPENV" = '1' ]]; then
		pacstrap /mnt gnome gnome-tweaks
		arch-chroot /mnt bash -c "systemctl enable --now gdm && exit"
		sed -i 's/#W/W/' /mnt/etc/gdm/custom.conf #Wayland dont work good with nvidia
	elif [[ "$DESKTOPENV" = '2' ]]; then
		pacstrap /mnt deepin lightdm
		arch-chroot /mnt bash -c "systemctl enable --now lightdm && exit"
	elif [[ "$DESKTOPENV" = '3' ]]; then
		pacstrap /mnt xorg-server plasma sddm
		arch-chroot /mnt bash -c "systemctl enable --now sddm && exit"
	elif [[ "$DESKTOPENV" = '4' ]]; then
		pacstrap /mnt xfce4 xorg-server lightdm lightdm-gtk-greeter gtk-engine-murrine gtk-engines xfce4-screenshooter \
			xfce4-whiskermenu-plugin xfce4-pulseaudio-plugin xfce4-battery-plugin network-manager-applet \
			gvfs gvfs-mtp mtpfs thunar-media-tags-plugin thunar-archive-plugin accountsservice xdg-desktop-portal
		arch-chroot /mnt bash -c "systemctl enable --now lightdm && exit"
		sed -i 's|#greeter-hide-users=false|greeter-hide-users=true|g' /mnt/etc/lightdm/lightdm.conf
	elif [[ "$DESKTOPENV" = '5' ]]; then
		pacstrap /mnt xorg-server network-manager-applet lxqt xdg-utils sddm
		arch-chroot /mnt bash -c "systemctl enable --now sddm && exit"
	fi
}

main() {
	echo -e "These Steps Are Available For Installion [Usually choose 1].\n"
	echo "1.  Update Pacman Database"
	echo "2.  Partitioning"
	echo "3.  Mount"
	echo "4.  Base Arch"
	echo "5.  Chroot"
	echo "6.  DesktopEnv"
	br && read -rp "Enter the number of step [1-6]: " stepno && clear

	array=(updates partition mounter base chrooot denv)
	stepno=$((stepno - 1))
	while [ $stepno -lt ${#array[*]} ]; do
		${array[$stepno]}
		stepno=$((stepno + 1))
	done
}

# STEPS
clear && ascii && br
main
sed -i 's|CacheDir|#CacheDir|g' /mnt/etc/pacman.conf && sync
umount -fv /mnt && wait
umount -fv /mnt/home && wait
umount -fv /mnt/boot/efi && wait
swapoff -av && wait
lsblk && br && read -rp 'Do you want to reboot [Y/N]: ' REBOOTYN
if [ "$REBOOTYN" = 'y' ] || [ "$REBOOTYN" = 'Y' ]; then reboot; fi
