#!/usr/bin/env bash
clear && LC_ALL=C && LANG=C
br() { for ((i = 1; i <= $(tput cols); i++)); do echo -n -; done; }

# Set Variables
UHOST() {
	read -rp "Enter new username for user [Only small character without symbol]: " USERN
	read -rp "Enter new Hostname/Machine-Name: " HNAME
}
RNAME="$(
	curl -sL --fail https://ipapi.co/timezone
	echo
)"
br && UHOST && br && echo -e "USERNAME = $USERN\nHOSTNAME = $HNAME\nREGION = $RNAME"
read -rp "Is above data correct? [Y/N]: " DATAYN
if [[ "$DATAYN" =~ ^[Yy]$ ]]; then br; else br && UHOST; fi

# Time
ln -sf /usr/share/zoneinfo/"$RNAME" /etc/localtime
hwclock --systohc

# Locale
sed -i 's/#en_US.UTF-8/en_US.UTF-8/g' /etc/locale.gen && locale-gen
echo -e 'LANG=en_US.UTF-8\nLANGUAGE=en_US\nLC_ALL=C' >/etc/locale.conf

# HOSTNAME
echo "$HNAME" >/etc/hostname
echo -e "127.0.0.1 $HNAME\n::1 $HNAME\n127.0.1.1 $HNAME.localdomain $HNAME" >/etc/hosts

# Root User
br && echo "Setting new Root/Sudo/Admin password [Keep powerfull password in mind]"
if compgen -g | grep &>/dev/null; then true; else groupadd sudo; fi
until passwd || ((count++ >= 5)); do echo 'TryAgain'; done
passwd -l root # Disable root login by default

# Normal User
# m=MakeNewUsrDir U=MakeNewUserGroup s=ShellIn/etc/shells
br && echo "Enter powerfull password for new user \"$USERN\" [Keep powerfull password in mind]"
useradd -m -U -G wheel,users,games,power,optical,storage,audio,video -s /bin/bash "$USERN"
chown -R "$USERN":users /home/"$USERN"
until passwd "$USERN" || ((count++ >= 5)); do echo 'Try Again' && br; done
sed -i 's/^#\s*\(%wheel\s\+ALL=(ALL)\s\+ALL\)/\1/' /etc/sudoers

# Paru
br && read -rp 'Do you want to install paru [Aur helper][Y/N]: ' PARUYN
if [[ "$PARUYN" =~ ^[Yy]$ ]]; then
	if [ -z "$USERN" ]; then read -rp 'Tell username you setted back [This is due to error last time] : ' USERN; else true; fi
	sudo -H -u "$USERN" bash -c 'if [[ -f "$HOME/paru" ]]; then true; else git clone --depth=1 https://aur.archlinux.org/paru-bin.git $HOME/paru; fi'
	sudo -H -u "$USERN" bash -c 'chmod -R 777 $HOME/paru && cd $HOME/paru && makepkg -s -i -c --noconfirm && rm -rf $HOME/paru'
fi

# GRUB
grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=Arch
grub-mkconfig -o /boot/grub/grub.cfg
sed -i 's|GRUB_TIMEOUT=5|GRUB_TIMEOUT=1|g' /etc/default/grub
sed -i 's|#GRUB_DISABLE_SUBMENU=y|GRUB_DISABLE_SUBMENU=y|g' /etc/default/grub
sed -i 's|GRUB_DISABLE_RECOVERY=true|GRUB_DISABLE_RECOVERY=false|g' /etc/default/grub

# Pacman
pacman-key --init
pacman-key --populate archlinux
sed -i '93s|#\[|\[|g' /etc/pacman.conf && sed -i '94s|#I|I|g' /etc/pacman.conf # Multilib
#sed -i "/\[multilib\]/,/Include/"'s/^#//' /etc/pacman.conf
sed -i 's|#Color|Color|g' /etc/pacman.conf                     # Color
sed -i 's|#VerbosePkgLists|VerbosePkgLists|g' /etc/pacman.conf # VerbosePkgLists

# Nano
sed -i 's|# include|include|' /etc/nanorc

# Firewall
ufw default deny incoming
ufw default allow outgoing
ufw enable

# Fancontrol
#sensors-detect --auto && sensors && pwmconfig

# NetworkManager
systemctl enable --now NetworkManager
systemctl enable --now ufw
systemctl enable --now --user pipewire{,-pulse,-media-session}
systemctl enable --now fstrim fstrim.timer
systemctl enable --now fancontrol thermald

# Fix touchpad
TEMPC="GRUB_CMDLINE_LINUX_DEFAULT=\"i8042.nopnp nowatchdog loglevel=4\""
sed -i "s|GRUB_CMDLINE_LINUX_DEFAULT=.*|$TEMPC|g" /etc/default/grub

# Enable swap
if [ -e /swapfile ]; then echo /swapfile already exists, skiping; else
	dd if=/dev/zero of=/swapfile count=6144 bs=1M status=progress && chmod -R 600 /swapfile
	echo -e '\n# Swap\n/swapfile swap swap defaults 0 0' >>/etc/fstab
	mkswap /swapfile && swapon /swapfile
fi

# Hibernation
br && read -rp "Do you want to enable hibernation support? [SWAPFILE=4GB(Default)][Edit script if system is encrypted][Y/N]: " HIBERYN
if [[ "${HIBERYN}" =~ ^[Yy]$ ]]; then
	sed -i "s|HOOKS=(base.*|HOOKS=(base udev autodetect modconf block filesystems keyboard resume fsck)|g" /etc/mkinitcpio.conf
	ROOTUUID="$(findmnt -no UUID -T /swapfile)"
	SWAPOFFSET="$(filefrag -v /swapfile | awk '{ if($1=="0:"){print substr($4, 1, length($4)-2)} }')"
	TEMPCMDLINE="GRUB_CMDLINE_LINUX_DEFAULT=\"i8042.nopnp nowatchdog loglevel=4 resume=UUID=$ROOTUUID resume_offset=$SWAPOFFSET\""
	sed -i "s/GRUB_CMDLINE_LINUX_DEFAULT=.*/$TEMPCMDLINE/g" /etc/default/grub
	grub-mkconfig -o /boot/grub/grub.cfg && mkinitcpio -P
else exit; fi
