#!/usr/bin/env bash
clear && LC_ALL=C && LANG=C
echo -e "export EDITOR='nano'" >>/etc/profile.d/env.sh && chmod a+x /etc/profile.d/env.sh
br() { for ((i = 1; i <= $(tput cols); i++)); do echo -n -; done; }

# Set Variables
read -rp "Enter the username for new user [Only small character without symbol]: " USERN
read -rp "Enter the hostname/Machine-Name: " HNAME
read -rp "Enter Region/Zone Eg.Asia/Kolkata: " RNAME
br && echo -e "USERNAME = $USERN\nHOSTNAME = $HNAME\nREGION/ZONE = $RNAME"
read -rp "Is above data correct? [Y/N]: " DATAYN
if [[ "$DATAYN" =~ ^[Yy]$ ]]; then true; else exit; fi

# Time & Locale
ln -sf /usr/share/zoneinfo/"$RNAME" /etc/localtime
timedatectl set-ntp true && hwclock --systohc
sed -i 's/#en_US.UTF-8/en_US.UTF-8/g' /etc/locale.gen && locale-gen
echo 'LANG=en_US.UTF-8' >/etc/locale.conf

# HOSTNAME
echo "$HNAME" >/etc/hostname
echo -e "127.0.0.1 $HNAME\n::1 $HNAME\n127.0.1.1 $HNAME.localdomain $HNAME" >/etc/hosts

# ROOT-PASSWORD
br && echo "Setting new Root/Sudo/Admin password [Keep powerfull password in mind]"
if compgen -g | grep &>/dev/null; then true; else groupadd sudo; fi
passwd
passwd -l root # Disable root login by default

# NEWUSER-&-PASSWORD # m=MakeNewUsrDir U=MakeNewUserGroup s=ShellIn/etc/shells
br && echo "Enter powerfull password for new user \"$USERN\" [Keep powerfull password in mind]"
useradd -m -U -G wheel,users,games,power,optical,storage,audio,video -s /bin/bash "$USERN"
chown -R "$USERN":users /home/"$USERN"
passwd "$USERN"
EDITOR=nano sed -i 's/^#\s*\(%wheel\s\+ALL=(ALL)\s\+ALL\)/\1/' /etc/sudoers

# Paru
read -rp 'Do you want to install paru [Aur helper][Y/N]: ' PARUYN
if [[ "$PARUYN" =~ ^[Yy]$ ]]; then
	if [ -z "$USERN" ]; then read -rp 'Tell username you setted back [This is due to error last time] : ' USERN; else true; fi
	sudo -H -u "$USERN" bash -c 'if [[ -f "$HOME/paru" ]]; then true; else git clone --depth=1 https://aur.archlinux.org/paru-bin.git $HOME/paru; fi'
	sudo -H -u "$USERN" bash -c 'chmod -R 777 $HOME/paru && cd $HOME/paru && makepkg -s -i -c --noconfirm && rm -rf $HOME/paru'
fi

# Add chromium pacman config
curl -s 'https://download.opensuse.org/repositories/home:/ungoogled_chromium/Arch/x86_64/home_ungoogled_chromium_Arch.key' | pacman-key -a -
if grep home_ungoogled_chromium_Arch /etc/pacman.conf &>/dev/null; then
	echo 'Chromium already exist in pacman.conf'
else
	echo -e '\n[home_ungoogled_chromium_Arch]\nSigLevel = Required TrustAll' | tee -a /etc/pacman.conf
	echo -e 'Server = https://download.opensuse.org/repositories/home:/ungoogled_chromium/Arch/$arch' | tee -a /etc/pacman.conf
fi

# Pacman
pacman-key --init && pacman-key --populate archlinux
sed -i '93s|#\[|\[|g' /etc/pacman.conf && sed -i '94s|#I|I|g' /etc/pacman.conf # Multilib
sed -i 's|#Color|Color|g' /etc/pacman.conf                                     # Color
sed -i 's|#VerbosePkgLists|VerbosePkgLists|g' /etc/pacman.conf                 # VerbosePkgLists

# NetworkManager
pacman -Sy --needed --noconfirm networkmanager && systemctl enable --now NetworkManager

# Firewall
pacman -S --needed --noconfirm ufw && systemctl enable --now ufw
ufw default deny incoming && ufw default allow outgoing && ufw enable

# Bluetooth
pacman -S --needed --noconfirm bluez blueman

# Pipewire
pacman -S --needed --noconfirm pavucontrol pipewire{,-pulse,-media-session}
systemctl enable --now --user pipewire{,-pulse,-media-session}

# Fstrim
systemctl enable --now fstrim fstrim.timer

# GRUB
grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=Arch && grub-mkconfig -o /boot/grub/grub.cfg
sed -i 's|GRUB_TIMEOUT=5|GRUB_TIMEOUT=1|g' /etc/default/grub
sed -i 's|#GRUB_DISABLE_SUBMENU=y|GRUB_DISABLE_SUBMENU=y|g' /etc/default/grub
sed -i 's|GRUB_DISABLE_RECOVERY=true|GRUB_DISABLE_RECOVERY=false|g' /etc/default/grub

# Fix touchpad
TEMP2="GRUB_CMDLINE_LINUX_DEFAULT=\"i8042.nopnp nowatchdog loglevel=4\""
sed -i "s|GRUB_CMDLINE_LINUX_DEFAULT=.*|$TEMP2|g" /etc/default/grub

# Enable Hibernation
if [ -e /swapfile ]; then echo /swapfile already exists, skiping; else
	dd if=/dev/zero of=/swapfile count=6144 bs=1M status=progress && chmod -R 600 /swapfile
	echo -e '\n# Swap\n/swapfile swap swap defaults 0 0' >>/etc/fstab
	mkswap /swapfile && swapon /swapfile
	br && read -rp "Do you want to enable hibernation support? [SWAPFILE=4GB(Default)][Edit script if system is encrypted][Y/N]: " HIBERYN
	if [[ "${HIBERYN}" =~ ^[Yy]$ ]]; then
		sed -i "s|HOOKS=(base.*|HOOKS=(base udev autodetect modconf block filesystems keyboard resume fsck)|g" /etc/mkinitcpio.conf
		RUUID="$(findmnt -no UUID -T /swapfile)"
		SOFFSET="$(filefrag -v /swapfile | awk '{ if($1=="0:"){print substr($4, 1, length($4)-2)} }')"
		TEMPCMDLINE="GRUB_CMDLINE_LINUX_DEFAULT=\"i8042.nopnp nowatchdog loglevel=4 resume=UUID=$RUUID resume_offset=$SOFFSET\""
		sed -i "s/GRUB_CMDLINE_LINUX_DEFAULT=.*/$TEMPCMDLINE/g" /etc/default/grub
		grub-mkconfig -o /boot/grub/grub.cfg
		mkinitcpio -P
	else exit; fi
fi
