#!/usr/bin/env bash
# CREDITS: https://wiki.manjaro.org/index.php/Improve_Font_Rendering
# Download some nice font
pacman -S --needed noto-fonts noto-fonts-emoji

# Some var
export SUSER="${SUDO_USER:-${USER}}"
noroot() {
	sudo -H -u "$SUSER" bash -c "$1"
}

# Make .Xresources
mkdir -pv /etc/X11/Xresources
echo -e 'Xft.lcdfilter: lcddefault
Xft.antialias: 1
Xft.autohint: 0
Xft.hinting: 1
Xft.dpi: 96
Xft.hintstyle: hintfull
Xft.rgba: rgb' >/etc/X11/Xresources/sharp-fonts
xrdb -merge /etc/X11/Xresources/sharp-fonts

# Fix fonts
ln -s /usr/share/fontconfig/conf.avail/10-sub-pixel-rgb.conf /etc/fonts/conf.d/
ln -s /usr/share/fontconfig/conf.avail/11-lcdfilter-default.conf /etc/fonts/conf.d/
ln -s /usr/share/fontconfig/conf.avail/10-hinting-full.conf /etc/fonts/conf.d/

# Font config
fc-cache -rsfv
