#!/bin/env bash
clear && LC_ALL=C && LANG=C

# Check Internet
if [ "$EUID" -ne 0 ]; then
    echo "Please run as root" && exit
    if : >/dev/tcp/8.8.8.8/53; then
        echo ''
    else echo 'offline Please connect...' && exit; fi
fi

# Replace bashrc
mv "$HOME"/.bashrc "$HOME"/.bashrc.bak
curl -LO https://raw.githubusercontent.com/Jrchintu/CDN/main/DOT/.bashrc
mv -i ./.bashrc "$HOME"/

# check distro type [debian,arch]
DISTRO="$(awk '/^ID=/' /etc/*-release | awk -F'=' '{ print tolower($2) }')"
if [ "$DISTRO" = 'arch' ]; then
    which pacman && echo arch
    pacman -Syu # Arch btw
    read -r 'Do you want AOSP env setup ?:' aospenv
    if [ "${aospenv}" = "y" ]; then
        curl -LO https://git.io/JB2VN && chmod a+x JB2VN && ./JB2VN
        echo 'Aosp env setup done'
    fi

elif [ "$DISTRO" = 'debian' ]; then
    which apt-get && echo debian || which apt && echo debian
    apt update && apt upgrade && apt autoremove --purge
else
    echo 'I am retard now'
fi

# Git config
git config --global user.name "Jrchintu"
git config --global user.email "harrypetersun@outlook.com"
git config --global color.ui auto
