#!/bin/bash

# Generate initramfs
mkinitcpio -P

# Set root password
echo "Set root password"
passwd

#Install needed software
pacman -S git \
nano \
bash-completion \
grub \
efibootmgr \
intel-ucode \
networkmanager \
ufw \
pulseaudio \
pulseaudio-alsa \
bluez \
bluez-utils \
pulseaudio-bluetooth --noconfirm --needed

# Set locale to en_US.UTF-8 UTF-8
sed -i '/en_US.UTF-8 UTF-8/s/^#//g' /etc/locale.gen
locale-gen
echo "LANG=en_US.UTF-8" >> /etc/locale.conf

# Set hostname
echo "3542" >> /etc/hostname
echo "127.0.1.1 3542.localdomain 3542" >> /etc/hosts

# Set date time
timedatectl set-timezone Asia/Kolkata
timedatectl set-ntp true
timedatectl status
ln -sf /usr/share/zoneinfo/Asia/Kolkata /etc/localtime
hwclock --systohc

# Install grub with efi
grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=arch
grub-mkconfig -o /boot/grub/grub.cfg

# Firewall setup
ufw default deny incoming
ufw default allow outgoing
ufw enable

# Enable service
systemctl enable ly.service
systemctl enable bluetooth.service
systemctl enable NetworkManager.service
systemctl enable ufw.service

# add new user
useradd -m -G wheel,power,input,storage,uucp,network -s /usr/bin/zsh chintu
sed --in-place 's/^#\s*\(%wheel\s\+ALL=(ALL)\s\+NOPASSWD:\s\+ALL\)/\1/' /etc/sudoers
echo "Set password for new user chintu"
passwd chintu

#EXIT
echo "Configuration done. You can now exit chroot."
